name: Static analysis

on: [pull_request]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: setup init_script
    #   shell: bash
    #   run: |
    #     echo "#!/bin/bash
    #     add-apt-repository ppa:oibaf/graphics-drivers
    #     apt update
    #     apt upgrade
    #     apt install -y libvulkan1 mesa-vulkan-drivers vulkan-utils" > init_script.sh

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      # with:
        # Exclude any issues found in ${Project_root_dir}/lib
        # exclude_dir: lib

        # Additional apt packages that need to be installed before running Cmake
        # apt_pckgs: software-properties-common libglu1-mesa-dev freeglut3-dev mesa-common-dev

        # Additional script that will be run (sourced) AFTER 'apt_pckgs' and before running Cmake
        # init_script: init_script.sh
